apiVersion: v1
kind: Service
metadata:
  name: product-department-clf
  labels:
    app: product-department-clf
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30003
    protocol: TCP
  selector:
    app: product-department-clf
